version: '3'

services:
  # Manually start the zkfc daemon on each of the machines that runs a NameNode. 
  # $hdfs start zkfc
  # hdfs zkfc -formatZK
  
  namenode1:
    image: sabaicode/hadoop_namenode:latest
    container_name: namenode1
    # restart: always
    ports:
      - 9870:9870  # Old hadoop use 50070
    volumes:
      - ./hadoop_namenode1:/opt/hadoop/data/namenode
      - ./hadoop_namenode1_logs:/opt/hadoop/logs
      - ./config/namenode/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/namenode/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    networks:
      - bigdata_hadoop
    # In hadoop HA cluster we format only primary namenode data. The below Command should run in order
    # $hdfs namenode -format
    # You should run this command only once. Running it on an already initialized shared edits directory may cause data loss.
    # $hdfs namenode -initializeSharedEdits
    # $hdfs --daemon start namenode
    # Run on Active Namenode
    # $hdfs zkfc -formatZK
    
    # Run all namenode
    # $hdfs --daemon start zkfc
    # command: ["hdfs", "--daemon", "start", "namenode"]
    command: ["tail", "-f", "/dev/null"]

  namenode2:
    image: sabaicode/hadoop_namenode:latest
    container_name: namenode2
    ports:
      - 9871:9870  # Old hadoop use 50070
    volumes:
      - ./hadoop_namenode2:/opt/hadoop/data/namenode
      - ./config/namenode/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/namenode/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    networks:
      - bigdata_hadoop
    # Run first time name start
    # $hdfs namenode -bootstrapStandby
    # Run every time namenode2 start
    # $hdfs --daemon start namenode
    # $hdfs --daemon start zkfc
    command: ["tail", "-f", "/dev/null"]

  journalnode1:
    image: sabaicode/hadoop_namenode:latest
    container_name: journalnode1
    networks:
      - bigdata_hadoop
    volumes:
      - ./config/journalnode/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/journalnode/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    command: ["hdfs", "journalnode"]

  journalnode2:
    image: sabaicode/hadoop_namenode:latest
    container_name: journalnode2
    networks:
      - bigdata_hadoop
    volumes:
      - ./config/journalnode/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/journalnode/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    command: ["hdfs", "journalnode"]

  journalnode3:
    image: sabaicode/hadoop_namenode:latest
    container_name: journalnode3
    networks:
      - bigdata_hadoop
    volumes:
      - ./config/journalnode/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/journalnode/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    command: ["hdfs", "journalnode"]

  zookeeper1:
    image: sabaicode/zookeeper:latest
    container_name: zookeeper1
    networks:
      - bigdata_hadoop
    ports:
      - "2181:2181"
    volumes:
      - ./config/zookeeper/zoo.cfg/:/opt/zookeeper/conf/zoo.cfg
    command: ["./bin/zkServer.sh", "start-foreground"]

  zookeeper2:
    image: sabaicode/zookeeper:latest
    container_name: zookeeper2
    networks:
      - bigdata_hadoop
    ports:
      - "2182:2181"
    volumes:
      - ./config/zookeeper/zoo.cfg/:/opt/zookeeper/conf/zoo.cfg
    command: ["./bin/zkServer.sh", "start-foreground"]

  zookeeper3:
    image: sabaicode/zookeeper:latest
    container_name: zookeeper3
    networks:
      - bigdata_hadoop
    ports:
      - "2183:2181"
    volumes:
      - ./config/zookeeper/zoo.cfg/:/opt/zookeeper/conf/zoo.cfg
    command: ["./bin/zkServer.sh", "start-foreground"]

  datanode1:
    image: sabaicode/hadoop_datanode:latest
    container_name: datanode1
    networks:
      - bigdata_hadoop
    volumes:
      - ./hadoop_datanode/datanode1:/opt/hadoop/data/datanode
      - ./config/datanode/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/datanode/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    ports:
      - '9864:9864'

  datanode2:
    image: sabaicode/hadoop_datanode:latest
    container_name: datanode2
    networks:
      - bigdata_hadoop
    volumes:
      - ./hadoop_datanode/datanode2:/opt/hadoop/data/datanode
      - ./config/datanode/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/datanode/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    ports:
      - '9865:9864'

  datanode3:
    image: sabaicode/hadoop_datanode:latest
    container_name: datanode3
    networks:
      - bigdata_hadoop
    volumes:
      - ./hadoop_datanode/datanode3:/opt/hadoop/data/datanode
      - ./config/datanode/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/datanode/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    ports:
      - '9866:9864'

networks:
  bigdata_hadoop: